# Generated by Django 3.2.8 on 2024-05-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound', '0003_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Other', 'Other')], default='English', max_length=50),
            preserve_default=False,
        ),
    ]
